minVersion: '0.22.2'
github:
    owner: getsentry
    repo: sentry-ruby
changelogPolicy: simple
preReleaseCommand: ruby .scripts/batch_release.rb
targets:
    - name: gem
    - name: registry
      type: sdk
      config:
          canonical: 'gem:sentry-ruby'
    - name: registry
      type: sdk
      config:
          canonical: 'gem:sentry-ruby-core'
    - name: registry
      type: sdk
      config:
          canonical: 'gem:sentry-rails'
    - name: registry
      type: sdk
      config:
          canonical: 'gem:sentry-sidekiq'
    - name: registry
      type: sdk
      config:
          canonical: 'gem:sentry-delayed_job'
    - name: github
