minVersion: '0.9.0'
github:
    owner: getsentry
    repo: raven-ruby
changelogPolicy: simple
statusProvider: 
    name: github
preReleaseCommand: ""
targets:
    - name: github
    - name: registry
      type: sdk
      config:
          canonical: 'gem:sentry-raven'
