inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'lib/raven/okjson.rb'
    - 'lib/raven/backports/uri.rb'

Lint/UnusedMethodArgument:
  Exclude:
     - 'lib/raven/backports/uri.rb'

Style/SignalException:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
