language: ruby
dist: trusty
sudo: false
group: beta
cache: bundler

branches:
  only: [master]

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1

env:
  - RAILS_VERSION=4
  - RAILS_VERSION=5
  - RAILS_VERSION=0

addons:
  apt:
    packages:
      - haveged

before_install:
  - service haveged start

matrix:
  include:
    - rvm: 1.9
      env: RAILS_VERSION=4
    - rvm: jruby-1.7.27
      env: JRUBY_OPTS="--dev" RAILS_VERSION=4
    - rvm: jruby-9.1.13.0
      env: JRUBY_OPTS="--dev -J-Djruby.launch.inproc=true -J-Xmx1024M" RAILS_VERSION=4
    - rvm: jruby-9.1.13.0
      env: JRUBY_OPTS="--dev -J-Djruby.launch.inproc=true -J-Xmx1024M" RAILS_VERSION=5
    - rvm: ruby-head
      env: RAILS_VERSION=0
  allow_failures:
    - rvm: ruby-head
