minVersion: '0.13.2'
github:
    owner: getsentry
    repo: raven-ruby
changelogPolicy: simple
preReleaseCommand: ruby .scripts/bump-version.sh
statusProvider:
  name: github
artifactProvider:
  name: github
targets:
    - name: gem
    - name: github
    - name: registry
      type: sdk
      config:
          canonical: 'gem:sentry-rails'
