name: sentry-rails Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'sentry-rails/**'
      - 'sentry-ruby/**'
jobs:
  test-sentry-rails:
    defaults:
      run:
        working-directory: sentry-rails
    name: Test on ruby ${{ matrix.ruby_version }} and rails ${{ matrix.rails_version }}
    runs-on: ${{ matrix.os }}
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        rails_version: [5.0.0, 5.1.0, 5.2.0, 6.0.0, 6.1.0]
        ruby_version: [2.4, 2.5, 2.6, 2.7, '3.0', jruby]
        os: [ubuntu-latest]
        include:
          - ruby_version: '3.0'
            rails_version: 6.1.0
            env: RUBYOPT="--enable-frozen-string-literal --debug=frozen-string-literal"
        exclude:
          - ruby_version: 2.4
            rails_version: 6.0.0
          - ruby_version: 2.4
            rails_version: 6.1.0
          - ruby_version: '3.0'
            rails_version: 5.0.0
          - ruby_version: '3.0'
            rails_version: 5.1.0
          - ruby_version: '3.0'
            rails_version: 5.2.0
          - ruby_version: jruby
            rails_version: 6.1.0

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: ruby/setup-ruby@v1
      with:
        bundler: 1
        ruby-version: ${{ matrix.ruby_version }}

    - name: Verify MySQL connection from host
      run: |
        sudo service mysql start
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"

    - name: Build with Rails ${{ matrix.rails_version }}
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
        DB_PORT: ${{ job.services.mysql.ports['3306'] }}
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake

  compare_allocation:
    defaults:
      run:
        working-directory: sentry-rails
    name: Compare memory allocation with ${{ matrix.ruby_version }} and rails ${{ matrix.rails_version }}
    runs-on: ${{ matrix.os }}
    needs: test-sentry-rails
    env:
      RAILS_VERSION: ${{ matrix.rails_version }}
    strategy:
      matrix:
        rails_version: [5.2, 6.1.0]
        ruby_version: [2.6, 2.7]
        os: [ubuntu-latest]
    steps:

    - name: Verify MySQL connection from host
      run: |
        sudo service mysql start
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"

    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: ruby/setup-ruby@v1
      with:
        bundler: 1
        ruby-version: ${{ matrix.ruby_version }}

    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Build and run allocation report on master
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec ruby benchmarks/allocation_comparison.rb

    - uses: actions/checkout@v1

    - name: Rebuild on the branch
      run: |
        bundle install --jobs 4 --retry 3
    - name: Run allocation report on the branch
      run: |
        bundle exec ruby benchmarks/allocation_comparison.rb
