name: sentry-delayed_job Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - \d+-\d+
  pull_request:
    paths:
      - 'sentry-*/**'
      - '!sentry-raven/**'
jobs:
  test:
    defaults:
      run:
        working-directory: sentry-delayed_job
    name: Test on ruby ${{ matrix.ruby_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby_version: [2.4, 2.5, 2.6, 2.7, '3.0', jruby]
        os: [ubuntu-latest]
        include:
          - ruby_version: '3.0'
            env: RUBYOPT="--enable-frozen-string-literal --debug=frozen-string-literal"
    steps:
    - uses: actions/checkout@v1
    - name: Install sqlite
      run: |
        # See https://github.community/t5/GitHub-Actions/ubuntu-latest-Apt-repository-list-issues/td-p/41122/page/2
        for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
        sudo apt-get update
        sudo apt-get install libsqlite3-dev

    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: ruby/setup-ruby@v1
      with:
        bundler: 1
        ruby-version: ${{ matrix.ruby_version }}

    - name: Run specs
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake
