name: sentry-ruby Test

on:
  push:
    branches:
      - master
      - release/**
  pull_request:
    paths:
      - 'sentry-ruby/**'
jobs:
  build:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6 # Not needed with a .ruby-version file
    - run: bundle install
    - run: gem build sentry-ruby.gemspec
    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.sha }}
        path: |
          ${{ github.workspace }}/*.gemspec
  test:
    defaults:
      run:
        working-directory: sentry-ruby
    name: Test on ruby ${{ matrix.ruby_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby_version: [2.4, 2.5, 2.6, 2.7, jruby]
        os: [ubuntu-latest]
        include:
          - ruby_version: 2.7
            env: RUBYOPT="--enable-frozen-string-literal --debug=frozen-string-literal"
    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: ruby/setup-ruby@v1
      with:
        bundler: 1
        ruby-version: ${{ matrix.ruby_version }}

    - name: Run specs
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake
